### ISSUE TITLE
Div with number of results not found

### ISSUE THREAD

**Issue by sq-xx** [pkrumins/xgoogle#1]
Search no longer works (tried with the "quick and dirty" example search with debug flag):
_extract_info() no longer findes a div 'ssb' element on the search page.
This may be due to changes/redesign in googles result pages.

**Comment by pkrumins** [comment]
That's true.

**Comment by sq-xx** [comment]
It looks like _extract_info() tries to extract the number of results (which seems no longer available).
But why not just count the number of actual results on a page?

**Comment by pkrumins** [comment]
That's doable.
